---
# This playbook contains stuff for XDP-tutorial

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

# Want have SSH-X11 forwarding working
- name: Packages - SSH-X11 packages
  dnf:
    name:
      - xorg-x11-xauth
      - xorg-x11-apps
    state: installed

# Ordinary developement tools
- name: Packages - Devel tools
  dnf:
    name:
      - git
      - make
      - cmake
      - gcc
      - gdb
      - autoconf
      - libtool
      - emacs
      - stgit
      - openssl-devel
      - cscope
      - pigz
    state: installed

- name: Packages - Devel tools eBPF
  dnf:
    name:
      - clang
      - llvm
    state: installed

- name: Packages - libbpf build dependencies
  dnf:
    name:
      - elfutils-libelf-devel
    state: installed

- name: Packages - Extra dependencies eBPF
  dnf:
    name:
      - binutils-devel
      - libcap-devel
    state: installed

- name: Packages - Devel tools eBPF extra for bpftrace
  dnf:
    name:
      - clang-devel
      - llvm-devel
    state: installed
