---
# This playbook contains stuff for XDP-tutorial

#
# Setup SSH keys
# - Hint: see group_vars/all
#
- name: SSH Authorized Keys
  authorized_key:
    user="{{ item }}"
    key="{{ ssh_public_key }}"
    state=present
  with_items:
    - fedora
    - root

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

# Want have SSH-X11 forwarding working
- name: Packages - SSH-X11 packages
  dnf:
    name:
      - xorg-x11-xauth
      - xorg-x11-apps
    state: installed

# Ordinary developement tools
- name: Packages - Devel tools
  dnf:
    name:
      - git
      - make
      - cmake
      - gcc
      - gdb
      - autoconf
      - libtool
      - emacs
      - vim
      - stgit
      - openssl-devel
      - cscope
      - pigz
    state: installed

- name: Packages - Devel tools eBPF
  dnf:
    name:
      - clang
      - llvm
      - kernel-headers
    state: installed

- name: Packages - libbpf build dependencies
  dnf:
    name:
      - elfutils-libelf-devel
    state: installed

- name: Packages - Extra dependencies eBPF
  dnf:
    name:
      - binutils-devel
      - libcap-devel
    state: installed

- name: Packages - Devel tools eBPF extra for bpftrace
  dnf:
    name:
      - clang-devel
      - llvm-devel
    state: installed

- name: Packages - XDP-tutorial required tools
  dnf:
    name:
      - ethtool
      - iputils
      - iproute-tc
      - bpftool
      - perf
      - perl-Time-HiRes
      - bash-completion
      - redhat-lsb-core
    state: installed
